language: node_js
node_js:
  - "8.9.4"

branches:
  only:
    - master

before_script:
  - npm i -g firebase-tools
  - npm i -g @angular/cli
  - npm i -g ionic
  - npm i -g cordova

script:
  - ionic build

after_success:
  - firebase deploy --token $FIREBASE_TOKEN

notifications:
  email:
    on_failure: change
    on_success: change
